### ISSUE TITLE
Expression serialization

### ISSUE THREAD

**Issue by biqas** [bartdesmet/ExpressionFutures#1]
@bartdesmet 
is this project in development or stopped? I watched on channel9 that you were referring to this project, but looking to the last commit, it is long ago?!

What are the plans to bring serialization for Expression trees? Do you have any timelines?

**Comment by grahamehorner** [comment]
Any update? thinking of expression serialisation for Azure IoT Edge devices and sensors

**Comment by bartdesmet** [comment]
Expression tree serialization was shipped as part of project Reaqtive, see https://github.com/reaqtive/reaqtor/tree/main/Nuqleon/Core/LINQ/Nuqleon.Linq.Expressions.Bonsai.Serialization.
