### ISSUE TITLE
Captured local variable crashes CSC

### ISSUE THREAD

**Issue by Pyromuffin** [bartdesmet/ExpressionFutures#3]
Not sure whether this should go in this repo or your branch of rosyln, but I've been playing around with CSharpExpressions, and found a pretty simple limitation:

void main()
{
int num = 5;
Expression<Action>> expr = () => num++;
}

Causes csc.exe to crash in ExpressionLambdaRewriter.cs, in the function VisitLocal(BoundLocal node), trying to access a key in _localMap that doesn't exist for the captured symbol.

I'm gonna try to mess around with the ExpressionLambdaRewriter, but i'm not a compiler dev, so I'm gonna try to do my best.

**Comment by Pyromuffin** [comment]
was able to work around it by changing the function to this:
```
     private BoundExpression VisitLocal(BoundLocal node)
        {
            if (node.ConstantValueOpt != null)
            {
                return Constant(node);
            }
            else
            {
                if (_localMap.TryGetValue(node.LocalSymbol, out var expr))
                {
                    return expr;
                }
                else
                {
                    return Constant(node);
                }
            }
        }
```

not quite sure that's the right thing to do, but it seems to work???

**Comment by bartdesmet** [comment]
Sorry for the (very) late reply, but good catch. This project is a bit of an on-and-off with bursts of attention (see https://github.com/bartdesmet/ExpressionFutures/issues/5 for some background info), and I just finished another wave of work on this over the holiday season. I addressed the issue above; your analysis and way to fix it was correct.
